### ISSUE TITLE
Zero value handling

### ISSUE THREAD

**Issue by swithek** [davseby/indc#36]
At the moment, it seems that the zero value might lead to some unexpected results:
```go
var sma SMA // not initialized with NewSMA
result, err := sma.Calc(data) // ???
```

I think Calc should return a specific error indicating whether the indicator was initialized or not.

**Comment by davseby** [comment]
In some cases due to market conditions denominators can be zero and returning an error I think would be illogical if its part of the indicator formula that we're using.

All of the cases that have intended such behavior now simply returns simply zero decimal.
